### ISSUE TITLE
Adding a Star joke option

### ISSUE THREAD

**Issue by RinkiTejwani** [Yash-srivastav16/Tell-Me-a-Joke-Javascript#1]
Hey , I would like to add a Star your Joke feature for the users to have a collection of their favourite joke . Can i please work on this functionality ?

**Comment by Yash-srivastav16** [comment]
Go On.. 🚀

**Comment by Yash-srivastav16** [comment]
Hye @RinkiTejwani I have merged your PR and it looks great thankyou for contributing. Apart from that quite suggestions you can do more in that
1-> A quick notification or something to know that the star button gets clicked.
2-> also a delete or clear all option in that Joke tab helps a lot... 

Thanks for contribution and sorry for delay..

**Comment by RinkiTejwani** [comment]
Thankyou it was great working with you
